defmodule Tiannara.Economics.RealityLedger do
  @moduledoc """
  Phase 21: The Economic Anchor.
  Translates abstract civilizational metrics into real-world fiat economics.
  Prevents the system from burning real money for abstract cognitive gains.
  """
  use GenServer
  require Logger

  # Real-world cost mappings
  @cost_per_llm_token 0.00003
  @cost_per_human_review 15.00

  def start_link(_opts), do: GenServer.start_link(__MODULE__, %{treasury: 10_000.0, revenue: 0.0}, name: __MODULE__)

  def init(args), do: {:ok, args}

  @doc """
  Records the real-world economic cost of a civilizational action.
  """
  def record_cost(action_type, units) do
    GenServer.call(__MODULE__, {:cost, action_type, units})
  end

  @doc """
  Records real-world revenue generated by a deployed Treaty milestone.
  """
  def record_revenue(source, amount_usd) do
    GenServer.call(__MODULE__, {:revenue, source, amount_usd})
  end

  def get_net_income, do: GenServer.call(__MODULE__, :net_income)

  # Handlers
  def handle_call({:cost, :llm_tokens, tokens}, _from, state) do
    cost = tokens * @cost_per_llm_token
    Logger.info("💸 [RealityLedger] Deducted $#{Float.round(cost, 4)} for LLM Inference.")
    {:reply, :ok, %{state | treasury: state.treasury - cost}}
  end

  def handle_call({:cost, :human_review, count}, _from, state) do
    cost = count * @cost_per_human_review
    Logger.warning("💸 [RealityLedger] Deducted $#{Float.round(cost, 2)} for Human-in-the-Loop Review.")
    {:reply, :ok, %{state | treasury: state.treasury - cost}}
  end

  def handle_call({:revenue, source, amount}, _from, state) do
    Logger.info("💰 [RealityLedger] Recognized $#{Float.round(amount, 2)} revenue from #{source}.")
    {:reply, :ok, %{state | revenue: state.revenue + amount}}
  end

  def handle_call(:net_income, _from, state) do
    net = state.revenue - (10_000.0 - state.treasury) # Revenue - Spend
    {:reply, net, state}
  end
end
