#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Production-grade Windows optimization for massive Elixir codebases.
.DESCRIPTION
    Bypasses NTFS/Defender bottlenecks and tunes OS-level scheduling for the BEAM VM.
#>

param (
    [string]$ProjectPath = (Get-Location).Path
)

Write-Host "🚀 Optimizing Windows for Elixir/BEAM Compilation..." -ForegroundColor Cyan

# 1. Granular Windows Defender Exclusions
Write-Host "🛡️  Configuring Windows Defender Exclusions..." -ForegroundColor Yellow
$exclusions = @(
    $ProjectPath,
    "$env:LOCALAPPDATA\elixir",
    "$env:ProgramFiles\Erlang OTP",
    "$env:ProgramFiles(x86)\Erlang OTP"
)

foreach ($path in $exclusions) {
    if (Test-Path $path) {
        Add-MpPreference -ExclusionPath $path -ErrorAction SilentlyContinue
    }
}

# Exclude specific high-churn extensions generated by Mix
Add-MpPreference -ExclusionExtension ".beam" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionExtension ".dump" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionProcess "erl.exe" -ErrorAction SilentlyContinue
Add-MpPreference -ExclusionProcess "elixir.exe" -ErrorAction SilentlyContinue

# 2. Set Global Environment Variables for BEAM Scheduling
Write-Host "⚙️  Tuning BEAM VM Scheduler Flags..." -ForegroundColor Yellow
[Environment]::SetEnvironmentVariable("ELIXIR_ERL_OPTIONS", "+sbwt none +sub true +sbt db", "User")

# 3. Disable NTFS Last Access Time Tracking
Write-Host "💾 Disabling NTFS Last Access Time Tracking..." -ForegroundColor Yellow
fsutil behavior set disablelastaccess 1 | Out-Null

Write-Host "✅ Optimization Complete! Restart your terminal for ENV vars to take effect." -ForegroundColor Green
