@echo off
echo Killing ALL Python processes...
taskkill /F /IM python.exe
echo Waiting for processes to terminate...
timeout /t 3 /nobreak >nul
echo Starting Tiannara API backend on port 8004...
python -m uvicorn tiannara_api.main:app --reload --port 8004
pause
