defmodule Tiannara.Sentinel.SOPL.SpeciesTracker do
  @moduledoc """
  SOPL-4: Sentinel Species Tracker
  
  Similar to Sentinel D.2 for epistemologies, this module tracks evolutionary
  metrics at the *LawSpecies* level rather than the universe level.
  It answers cosmological queries like "Which species generates the healthiest epistemologies?"
  """
  require Logger
  alias Tiannara.SOPL.LawSpecies

  @doc """
  Aggregates live telemetry from all universe instances belonging to a specific LawSpecies.
  """
  def aggregate_telemetry(species, universe_metrics, innovations, extinctions) do
    # Filter data specific to this species' universes
    my_metrics = Enum.filter(universe_metrics, fn m -> m.universe_id in species.universes end)
    
    # 1. Species Longevity (Average epochs survived across all instances)
    longevity = calculate_avg(my_metrics, & Map.get(&1, :epochs_survived, 0))
    
    # 2. Innovation Yield (How many genuine LawInnovations this species produced)
    # E.g. did it spawn successful descendants or just stall?
    yield = Enum.count(innovations, fn i -> i.proto_law_id in species.universes end)
    
    # 3. Civilizational Productivity
    productivity = calculate_avg(my_metrics, & Map.get(&1, :total_civilizations_spawned, 0))
    
    # 4. Truth Retention (Epistemological health generated by this environment)
    truth = calculate_avg(my_metrics, & Map.get(&1, :truth_retention_score, 0.0))
    
    # 5. Extinction Causes (Why instances of this species usually die)
    causes = Enum.filter(extinctions, fn e -> e.species_id == species.id end)
             |> Enum.map(& &1.primary_collapse_vector)
             |> Enum.frequencies()

    Logger.debug("🛰️ [Sentinel SOPL-4] Aggregated telemetry for Species #{species.id} (N=#{length(my_metrics)} instances)")

    %{
      species_id: species.id,
      longevity: longevity,
      innovation_yield: yield,
      civilizational_productivity: productivity,
      truth_retention: truth,
      extinction_frequencies: causes
    }
  end

  defp calculate_avg([], _fun), do: 0.0
  defp calculate_avg(items, fun) do
    sum = Enum.map(items, fun) |> Enum.sum()
    sum / length(items)
  end
end
