defmodule Tiannara.ToolForge.Adapters.APIEvolutionAdapter do
  alias Tiannara.ToolForge.Domain.{ToolSpecification, GeneratedTool}

  @api_evolution_url "http://localhost:8000"

  @spec evolve_api(ToolSpecification.t(), map()) :: {:ok, GeneratedTool.t()} | {:error, term()}
  def evolve_api(%ToolSpecification{} = spec, opts \\ %{}) do
    generations = Map.get(opts, :generations, 10)
    population_size = Map.get(opts, :population_size, 10)

    request_body = Jason.encode!(%{
      generations: generations,
      population_size: population_size
    })

    case http_post("#{@api_evolution_url}/evolve/sync", request_body) do
      {:ok, response} ->
        result = Jason.decode!(response)
        best_genome = Map.get(result, "best_genome", %{})
        fitness = Map.get(result, "best_fitness", 0.0)

        tool = GeneratedTool.new(%{
          spec_id: spec.id,
          name: spec.name,
          language: :python,
          source_files: extract_generated_files(result),
          entry_point: "main:app",
          fitness_score: fitness,
          build_instructions: "cd output/generated_api && uvicorn main:app --reload",
          generation_metadata: %{
            generator: :api_evolution_engine,
            generations: generations,
            population_size: population_size,
            best_fitness: fitness,
            genome: best_genome
          }
        })

        {:ok, tool}

      {:error, reason} ->
        {:error, {:api_evolution_failed, reason}}
    end
  end

  defp http_post(url, body) do
    try do
      {:ok, _status, _headers, response_body} =
        :httpc.request(:post, {String.to_charlist(url), [], ~c"application/json", body}, [], [])
      {:ok, List.to_string(response_body)}
    rescue
      e -> {:error, e}
    catch
      :exit, reason -> {:error, reason}
    end
  end

  defp extract_generated_files(result) do
    generated = Map.get(result, "generated_code", %{})
    if generated == %{} do
      %{"main.py" => "# Generated by API Evolution Engine\n# See output/generated_api/"}
    else
      generated
    end
  end
end
