defmodule TiannaraOS.Discovery do
  @moduledoc """
  Represents a discovery candidate or validated fact generated by grounding loops in TiannaraOS.
  """

  @derive Jason.Encoder
  defstruct [
    :id,                    # atom() - unique identifier
    :source_world,          # atom() - world ID where discovery originated
    :evidence_ids,          # list(atom()) - evidence IDs supporting this discovery
    :theory_ids,            # list(atom()) - related theory IDs
    :origin_program_id,     # atom() | nil
    :origin_institution_id, # atom() | nil
    :origin_world_id,       # atom() | nil
    validation_level: :l1,  # atom() - :l1, :l2, :l3, :l4, :l5
    status: :candidate,     # atom() - :candidate, :validated, :retired
    evidence_score: 0.0,    # float()
    replication_score: 0.0, # float()
    security_score: 0.0,    # float()
    novelty_score: 0.0,     # float()
    transferability_score: 0.0, # float()
    impact_score: 0.0,      # float()
    confidence: 1.0,        # float() - unified global confidence
    utility: 1.0,           # float() - usefulness metric
    relevance: 1.0,         # float() - MISSING PRIMITIVE #5: Innovation obsolescence (decays over time)
    validation_history: [], # list(map())
    metadata: %{}           # map() - arbitrary metadata
  ]

  @type t :: %__MODULE__{
    id: atom(),
    source_world: atom(),
    evidence_ids: [atom()],
    theory_ids: [atom()],
    origin_program_id: atom() | nil,
    origin_institution_id: atom() | nil,
    origin_world_id: atom() | nil,
    validation_level: :l1 | :l2 | :l3 | :l4 | :l5,
    status: :candidate | :validated | :retired,
    evidence_score: float(),
    replication_score: float(),
    security_score: float(),
    novelty_score: float(),
    transferability_score: float(),
    impact_score: float(),
    confidence: float(),
    utility: float(),
    relevance: float(),         # MISSING PRIMITIVE #5: Innovation obsolescence
    validation_history: [map()],
    metadata: map()
  }
end