defmodule Tiannara.AAL.LexicalTensegrityField do
  @moduledoc "Zero-latency intent parser using static semantic embeddings."
  
  alias Tiannara.AAL.SemanticEncoder
  alias Tiannara.Math

  @threshold 0.65 # Tuned for sparse vector cosine similarity

  # Pre-calculated sparse vectors for the 20 domains.
  # In production, these are generated by passing the domain's core axioms through SemanticEncoder.encode/1
  @domain_vectors %{
    engineering: SemanticEncoder.encode("hardware systems torsional rigidity schematics vhdl verilog"),
    medicine: SemanticEncoder.encode("proteomic decouplers mrna vaccine monoclonal antibody"),
    computation: SemanticEncoder.encode("polymorphic ast compilers bytecodes silicon topology"),
    materials: SemanticEncoder.encode("metallurgy nanotech crystalline grain boundaries tensile"),
    energy: SemanticEncoder.encode("quantum well capacitance atomic-layer energy cell storage"),
    cybernetics: SemanticEncoder.encode("homeostatic feedback controllers resonant frequencies"),
    architecture: SemanticEncoder.encode("autopoietic structural topologies self-healing grids")
    # In a full deployment, the remaining 13 domains would be mapped similarly.
  }

  @spec map_intent_vectors(String.t()) :: {atom(), [atom()]}
  def map_intent_vectors(raw_text) do
    input_vector = SemanticEncoder.encode(raw_text)

    engaged_domains = 
      @domain_vectors
      |> Enum.filter(fn {_domain, domain_vector} -> 
        Math.cosine_similarity(input_vector, domain_vector) > @threshold 
      end)
      |> Enum.map(fn {domain, _vector} -> domain end)

    # Fallback to :engineering if no domains cross the threshold (prevents empty extraction)
    engaged_domains = if engaged_domains == [], do: [:engineering], else: engaged_domains

    primary_intent = determine_core_action(input_vector)
    {primary_intent, engaged_domains}
  end
  
  defp determine_core_action(_vector), do: :synthesis 
end
