defmodule Tiannara.Observatory.Validation.Reporter do
  alias Tiannara.Observatory.Validation.MetricsStore

  def generate(campaign) do
    ticks = MetricsStore.get_all(campaign.id)
    %{markdown: render_markdown(campaign, ticks), html: render_html(campaign, ticks), summary: build_summary(campaign, ticks)}
  end

  defp build_summary(campaign, ticks) do
    total_checks = Enum.sum(Enum.map(ticks, & &1.passed)) + Enum.sum(Enum.map(ticks, & &1.failed))
    total_failures = Enum.sum(Enum.map(ticks, & &1.failed))
    total_warnings = Enum.sum(Enum.map(ticks, & &1.warnings))
    %{
      campaign_name: campaign.name, duration: campaign.duration, ticks: length(ticks),
      total_checks: total_checks, failures: total_failures, warnings: total_warnings,
      pass_rate: if(total_checks > 0, do: 1.0 - total_failures / total_checks, else: 1.0),
      verdict: verdict(total_failures, total_checks)
    }
  end

  defp verdict(0, _), do: :healthy
  defp verdict(f, t) when f / t < 0.05, do: :degraded
  defp verdict(_, _), do: :unhealthy

  defp render_markdown(campaign, ticks) do
    summary = build_summary(campaign, ticks)
    """
# Validation Report: #{campaign.name}

**Campaign ID:** `#{campaign.id}`
**Duration:** #{format_ms(campaign.duration)}
**Interval:** #{format_ms(campaign.interval)}
**Started:** #{campaign.started_at}
**Status:** #{campaign.status}

## Summary

| Metric | Value |
|--------|-------|
| Ticks Collected | #{summary.ticks} |
| Total Checks | #{summary.total_checks} |
| Failures | #{summary.failures} |
| Warnings | #{summary.warnings} |
| Pass Rate | #{Float.round(summary.pass_rate * 100, 2)}% |
| Verdict | **#{summary.verdict |> to_string() |> String.upcase()}** |

## Checks Performed

#{Enum.map_join(campaign.checks, "\n", fn c -> "- `#{c}`" end)}

## Failure Timeline

#{render_failure_timeline(ticks)}

## Constitutional Alignment

This campaign validates Tiannara's adherence to:
- **Verification First**: continuous runtime validation
- **Bottleneck Discovery**: active probing of all subsystems
- **Safety and Reliability**: anomaly detection and graceful degradation
- **Continuous Self-Evaluation**: ongoing health assessment

---
*Generated by Tiannara.Observatory.ValidationCampaign*
"""
  end

  defp render_html(campaign, ticks) do
    summary = build_summary(campaign, ticks)
    verdict_color = if(summary.verdict == :healthy, do: "#22c55e", else: "#ef4444")
    """
<!DOCTYPE html>
<html>
<head><title>Validation: #{campaign.name}</title>
<style>
  body { font-family: system-ui; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
  th { background: #f5f5f5; }
  .verdict { color: #{verdict_color}; font-weight: bold; font-size: 1.2em; }
  .fail { color: #ef4444; }
  .warn { color: #f59e0b; }
  .pass { color: #22c55e; }
</style>
</head>
<body>
<h1>#{campaign.name}</h1>
<p>Verdict: <span class="verdict">#{summary.verdict |> to_string() |> String.upcase()}</span></p>
<table>
  <tr><th>Ticks</th><td>#{summary.ticks}</td></tr>
  <tr><th>Checks</th><td>#{summary.total_checks}</td></tr>
  <tr><th>Failures</th><td class="fail">#{summary.failures}</td></tr>
  <tr><th>Warnings</th><td class="warn">#{summary.warnings}</td></tr>
  <tr><th>Pass Rate</th><td>#{Float.round(summary.pass_rate * 100, 2)}%</td></tr>
</table>
<h2>Failure Timeline</h2>
#{render_html_failures(ticks)}

</body>
</html>
"""
  end

  defp render_failure_timeline(ticks) do
    failures = ticks |> Enum.flat_map(fn tick ->
      tick.checks |> Enum.filter(fn {_, r} -> r.status == :fail end) |> Enum.map(fn {name, r} -> {tick.timestamp, name, r} end)
    end)
    if failures == [] do
      "_No failures detected._"
    else
      failures |> Enum.map_join("\n", fn {ts, name, r} -> "- **#{ts}** `#{name}`: #{r.message}" end)
    end
  end

  defp render_html_failures(ticks) do
    failures = ticks |> Enum.flat_map(fn tick ->
      tick.checks |> Enum.filter(fn {_, r} -> r.status in [:fail, :warn] end) |> Enum.map(fn {name, r} -> {tick.timestamp, name, r} end)
    end)
    if failures == [] do
      "<p class='pass'>No failures or warnings.</p>"
    else
      rows = Enum.map_join(failures, "\n", fn {ts, name, r} ->
        "<tr><td>#{ts}</td><td>#{name}</td><td class='#{r.status}'>#{r.status}</td><td>#{r.message}</td></tr>"
      end)
      "<table><tr><th>Time</th><th>Check</th><th>Status</th><th>Message</th></tr>#{rows}</table>"
    end
  end

  defp format_ms(ms) do
    cond do
      ms >= :timer.hours(1) -> "#{div(ms, :timer.hours(1))} hours"
      ms >= :timer.minutes(1) -> "#{div(ms, :timer.minutes(1))} minutes"
      true -> "#{div(ms, :timer.seconds(1))} seconds"
    end
  end
end
