"""
Explanation Audit Trail for Explainable ECM

Provides immutable, append-only logging of all explanations generated by the system.
Supports regulatory compliance (EU AI Act Article 13-15) with searchable audit records.

Key Features:
- Immutable SQLite-based storage with append-only writes
- Comprehensive metadata tracking (timestamps, user IDs, explanation types)
- Search and retrieval by multiple criteria (time range, node, type)
- Export capabilities for regulatory audits (JSON, CSV)
- Integrity verification with cryptographic hashing
- Retention policy management

Usage:
    from tiannara_core.interpretability.audit_trail import ExplanationAuditTrail
    
    trail = ExplanationAuditTrail(db_path="explanation_audit.db")
    
    # Log an explanation
    record_id = trail.log_explanation(
        explanation_text="The decision was made because...",
        explanation_type="causal_path",
        target_node="final_outcome",
        confidence=0.85,
        user_id="user_123"
    )
    
    # Search audit records
    records = trail.search_explanations(
        start_date="2026-04-01",
        end_date="2026-04-30",
        explanation_type="counterfactual"
    )
    
    # Export for compliance audit
    trail.export_audit_report("audit_report.json", format="json")

References:
    EU AI Act Articles 13-15: Transparency and explainability requirements
    GDPR Article 22: Right to explanation for automated decisions
"""

import logging
import sqlite3
import json
import hashlib
import csv
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Any, Tuple
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class AuditRecord:
    """Immutable audit record for an explanation."""
    record_id: str  # UUID or hash-based ID
    timestamp: str  # ISO format timestamp
    explanation_text: str  # The actual explanation
    explanation_type: str  # 'causal_path', 'counterfactual', 'narrative', etc.
    target_node: str  # Node being explained
    source_nodes: List[str] = field(default_factory=list)  # Source nodes in path
    confidence: float = 1.0  # Confidence score
    calibration_result: Optional[Dict] = None  # Calibration details if available
    user_id: Optional[str] = None  # Who requested the explanation
    session_id: Optional[str] = None  # Session context
    metadata: Dict[str, Any] = field(default_factory=dict)  # Additional context
    content_hash: str = ""  # SHA256 hash for integrity verification
    
    def compute_hash(self) -> str:
        """Compute SHA256 hash of explanation content for integrity verification."""
        content = json.dumps({
            'explanation_text': self.explanation_text,
            'explanation_type': self.explanation_type,
            'target_node': self.target_node,
            'timestamp': self.timestamp
        }, sort_keys=True)
        return hashlib.sha256(content.encode()).hexdigest()
    
    def verify_integrity(self) -> bool:
        """Verify that record hasn't been tampered with."""
        return self.content_hash == self.compute_hash()


class ExplanationAuditTrail:
    """
    Immutable audit trail for explanation logging and compliance tracking.
    
    Provides append-only SQLite storage with comprehensive search capabilities
    for regulatory compliance and system auditing.
    """
    
    def __init__(self, db_path: str = "explanation_audit.db", readonly: bool = False):
        """
        Initialize audit trail database.
        
        Args:
            db_path: Path to SQLite database file
            readonly: If True, open database in read-only mode
        """
        self.db_path = db_path
        self.readonly = readonly
        
        # Create database and schema
        self._initialize_database()
        
        logger.info(f"ExplanationAuditTrail initialized at {db_path}")
    
    def _initialize_database(self):
        """Create database schema if it doesn't exist."""
        conn = self._get_connection()
        try:
            cursor = conn.cursor()
            
            # Main audit table
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS explanation_records (
                    record_id TEXT PRIMARY KEY,
                    timestamp TEXT NOT NULL,
                    explanation_text TEXT NOT NULL,
                    explanation_type TEXT NOT NULL,
                    target_node TEXT NOT NULL,
                    source_nodes TEXT,  -- JSON array
                    confidence REAL DEFAULT 1.0,
                    calibration_result TEXT,  -- JSON object
                    user_id TEXT,
                    session_id TEXT,
                    metadata TEXT,  -- JSON object
                    content_hash TEXT NOT NULL,
                    created_at TEXT DEFAULT CURRENT_TIMESTAMP
                )
            """)
            
            # Indexes for efficient searching
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_timestamp 
                ON explanation_records(timestamp)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_explanation_type 
                ON explanation_records(explanation_type)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_target_node 
                ON explanation_records(target_node)
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_user_id 
                ON explanation_records(user_id)
            """)
            
            conn.commit()
            logger.debug("Database schema initialized")
            
        finally:
            conn.close()
    
    def _get_connection(self) -> sqlite3.Connection:
        """Get database connection."""
        if self.readonly:
            # Read-only mode for safety
            uri = f"file:{self.db_path}?mode=ro"
            conn = sqlite3.connect(uri, uri=True)
        else:
            conn = sqlite3.connect(self.db_path)
            # Enable WAL mode for better concurrent access
            conn.execute("PRAGMA journal_mode=WAL")
        return conn
    
    def log_explanation(
        self,
        explanation_text: str,
        explanation_type: str,
        target_node: str,
        source_nodes: Optional[List[str]] = None,
        confidence: float = 1.0,
        calibration_result: Optional[Dict] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Log an explanation to the audit trail (append-only).
        
        Args:
            explanation_text: The explanation content
            explanation_type: Type of explanation ('causal_path', 'counterfactual', etc.)
            target_node: The node being explained
            source_nodes: Source nodes in the causal path
            confidence: Confidence score for the explanation
            calibration_result: Calibration details if available
            user_id: User who requested the explanation
            session_id: Session context identifier
            metadata: Additional metadata
            
        Returns:
            record_id: Unique identifier for the audit record
        """
        if self.readonly:
            raise RuntimeError("Cannot write to read-only audit trail")
        
        # Generate record ID from timestamp and content
        timestamp = datetime.now().isoformat()
        record_id = hashlib.md5(
            f"{timestamp}{explanation_text[:50]}".encode()
        ).hexdigest()
        
        # Create audit record
        record = AuditRecord(
            record_id=record_id,
            timestamp=timestamp,
            explanation_text=explanation_text,
            explanation_type=explanation_type,
            target_node=target_node,
            source_nodes=source_nodes or [],
            confidence=confidence,
            calibration_result=calibration_result,
            user_id=user_id,
            session_id=session_id,
            metadata=metadata or {}
        )
        
        # Compute content hash for integrity
        record.content_hash = record.compute_hash()
        
        # Insert into database
        conn = self._get_connection()
        try:
            cursor = conn.cursor()
            cursor.execute("""
                INSERT INTO explanation_records (
                    record_id, timestamp, explanation_text, explanation_type,
                    target_node, source_nodes, confidence, calibration_result,
                    user_id, session_id, metadata, content_hash
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                record.record_id,
                record.timestamp,
                record.explanation_text,
                record.explanation_type,
                record.target_node,
                json.dumps(record.source_nodes),
                record.confidence,
                json.dumps(record.calibration_result) if record.calibration_result else None,
                record.user_id,
                record.session_id,
                json.dumps(record.metadata),
                record.content_hash
            ))
            conn.commit()
            
            logger.debug(f"Logged explanation record: {record_id}")
            return record_id
            
        finally:
            conn.close()
    
    def get_record(self, record_id: str) -> Optional[AuditRecord]:
        """
        Retrieve a specific audit record by ID.
        
        Args:
            record_id: The record identifier
            
        Returns:
            AuditRecord if found, None otherwise
        """
        conn = self._get_connection()
        try:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT * FROM explanation_records WHERE record_id = ?",
                (record_id,)
            )
            row = cursor.fetchone()
            
            if row is None:
                return None
            
            return self._row_to_record(row)
            
        finally:
            conn.close()
    
    def search_explanations(
        self,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        explanation_type: Optional[str] = None,
        target_node: Optional[str] = None,
        user_id: Optional[str] = None,
        min_confidence: Optional[float] = None,
        limit: int = 100,
        offset: int = 0
    ) -> List[AuditRecord]:
        """
        Search audit records with flexible filtering.
        
        Args:
            start_date: Filter records after this date (ISO format)
            end_date: Filter records before this date (ISO format)
            explanation_type: Filter by explanation type
            target_node: Filter by target node
            user_id: Filter by user ID
            min_confidence: Filter by minimum confidence score
            limit: Maximum number of records to return
            offset: Pagination offset
            
        Returns:
            List of matching AuditRecords
        """
        conn = self._get_connection()
        try:
            # Build query dynamically based on filters
            query = "SELECT * FROM explanation_records WHERE 1=1"
            params = []
            
            if start_date:
                query += " AND timestamp >= ?"
                params.append(start_date)
            
            if end_date:
                query += " AND timestamp <= ?"
                params.append(end_date)
            
            if explanation_type:
                query += " AND explanation_type = ?"
                params.append(explanation_type)
            
            if target_node:
                query += " AND target_node = ?"
                params.append(target_node)
            
            if user_id:
                query += " AND user_id = ?"
                params.append(user_id)
            
            if min_confidence is not None:
                query += " AND confidence >= ?"
                params.append(min_confidence)
            
            # Order by timestamp descending (most recent first)
            query += " ORDER BY timestamp DESC LIMIT ? OFFSET ?"
            params.extend([limit, offset])
            
            cursor = conn.cursor()
            cursor.execute(query, params)
            rows = cursor.fetchall()
            
            return [self._row_to_record(row) for row in rows]
            
        finally:
            conn.close()
    
    def get_statistics(self) -> Dict[str, Any]:
        """
        Get summary statistics about the audit trail.
        
        Returns:
            Dictionary with counts, date ranges, type distribution, etc.
        """
        conn = self._get_connection()
        try:
            cursor = conn.cursor()
            
            # Total count
            cursor.execute("SELECT COUNT(*) FROM explanation_records")
            total_count = cursor.fetchone()[0]
            
            if total_count == 0:
                return {"total_records": 0}
            
            # Date range
            cursor.execute("SELECT MIN(timestamp), MAX(timestamp) FROM explanation_records")
            min_date, max_date = cursor.fetchone()
            
            # Type distribution
            cursor.execute("""
                SELECT explanation_type, COUNT(*) as count 
                FROM explanation_records 
                GROUP BY explanation_type 
                ORDER BY count DESC
            """)
            type_distribution = dict(cursor.fetchall())
            
            # Average confidence
            cursor.execute("SELECT AVG(confidence) FROM explanation_records")
            avg_confidence = cursor.fetchone()[0]
            
            # Records per day (last 7 days)
            cursor.execute("""
                SELECT DATE(timestamp) as day, COUNT(*) as count
                FROM explanation_records
                WHERE timestamp >= datetime('now', '-7 days')
                GROUP BY day
                ORDER BY day DESC
            """)
            daily_counts = dict(cursor.fetchall())
            
            return {
                "total_records": total_count,
                "date_range": {
                    "earliest": min_date,
                    "latest": max_date
                },
                "type_distribution": type_distribution,
                "average_confidence": float(avg_confidence),
                "daily_counts_last_7_days": daily_counts
            }
            
        finally:
            conn.close()
    
    def export_audit_report(
        self,
        output_path: str,
        format: str = "json",
        start_date: Optional[str] = None,
        end_date: Optional[str] = None
    ) -> str:
        """
        Export audit records for compliance reporting.
        
        Args:
            output_path: Path to output file
            format: Export format ('json' or 'csv')
            start_date: Optional date filter
            end_date: Optional date filter
            
        Returns:
            Path to exported file
        """
        # Get filtered records
        records = self.search_explanations(
            start_date=start_date,
            end_date=end_date,
            limit=10000  # Large limit for export
        )
        
        if format == "json":
            return self._export_json(output_path, records)
        elif format == "csv":
            return self._export_csv(output_path, records)
        else:
            raise ValueError(f"Unsupported export format: {format}")
    
    def _export_json(self, output_path: str, records: List[AuditRecord]) -> str:
        """Export records as JSON."""
        export_data = {
            "export_timestamp": datetime.now().isoformat(),
            "total_records": len(records),
            "records": [asdict(record) for record in records]
        }
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(export_data, f, indent=2, ensure_ascii=False)
        
        logger.info(f"Exported {len(records)} records to {output_path}")
        return output_path
    
    def _export_csv(self, output_path: str, records: List[AuditRecord]) -> str:
        """Export records as CSV."""
        if not records:
            logger.warning("No records to export")
            return output_path
        
        fieldnames = [
            'record_id', 'timestamp', 'explanation_text', 'explanation_type',
            'target_node', 'source_nodes', 'confidence', 'calibration_result',
            'user_id', 'session_id', 'metadata', 'content_hash'
        ]
        
        with open(output_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            
            for record in records:
                row = asdict(record)
                # Convert lists/dicts to JSON strings for CSV
                row['source_nodes'] = json.dumps(row['source_nodes'])
                row['calibration_result'] = json.dumps(row['calibration_result']) if row['calibration_result'] else ''
                row['metadata'] = json.dumps(row['metadata'])
                writer.writerow(row)
        
        logger.info(f"Exported {len(records)} records to {output_path}")
        return output_path
    
    def verify_integrity(self) -> Dict[str, Any]:
        """
        Verify integrity of all audit records.
        
        Returns:
            Dictionary with verification results
        """
        conn = self._get_connection()
        try:
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM explanation_records")
            rows = cursor.fetchall()
            
            total_records = len(rows)
            valid_records = 0
            invalid_records = 0
            invalid_ids = []
            
            for row in rows:
                record = self._row_to_record(row)
                if record.verify_integrity():
                    valid_records += 1
                else:
                    invalid_records += 1
                    invalid_ids.append(record.record_id)
            
            return {
                "total_records": total_records,
                "valid_records": valid_records,
                "invalid_records": invalid_records,
                "integrity_verified": invalid_records == 0,
                "invalid_record_ids": invalid_ids
            }
            
        finally:
            conn.close()
    
    def delete_old_records(self, retention_days: int = 365) -> int:
        """
        Delete records older than retention period (for GDPR compliance).
        
        Args:
            retention_days: Number of days to retain records
            
        Returns:
            Number of records deleted
        """
        if self.readonly:
            raise RuntimeError("Cannot delete from read-only audit trail")
        
        cutoff_date = (datetime.now() - timedelta(days=retention_days)).isoformat()
        
        conn = self._get_connection()
        try:
            cursor = conn.cursor()
            cursor.execute(
                "DELETE FROM explanation_records WHERE timestamp < ?",
                (cutoff_date,)
            )
            deleted_count = cursor.rowcount
            conn.commit()
            
            logger.info(f"Deleted {deleted_count} records older than {retention_days} days")
            return deleted_count
            
        finally:
            conn.close()
    
    def _row_to_record(self, row: Tuple) -> AuditRecord:
        """Convert database row to AuditRecord."""
        return AuditRecord(
            record_id=row[0],
            timestamp=row[1],
            explanation_text=row[2],
            explanation_type=row[3],
            target_node=row[4],
            source_nodes=json.loads(row[5]) if row[5] else [],
            confidence=row[6],
            calibration_result=json.loads(row[7]) if row[7] else None,
            user_id=row[8],
            session_id=row[9],
            metadata=json.loads(row[10]) if row[10] else {},
            content_hash=row[11]
        )


def create_audit_trail(db_path: str = "explanation_audit.db") -> ExplanationAuditTrail:
    """
    Convenience function to create an audit trail instance.
    
    Args:
        db_path: Path to SQLite database
        
    Returns:
        ExplanationAuditTrail instance
    """
    return ExplanationAuditTrail(db_path=db_path)
