import type { CommandAction, RoomConfig } from '@/types'

export const ROOMS: RoomConfig[] = [
  { slug: 'runtime', name: 'Runtime', icon: '⚡', description: 'OTP, health, checkpoints, recovery' },
  { slug: 'science', name: 'Scientific Discovery', icon: '🔬', description: 'Discoveries, experiments, hypotheses' },
  { slug: 'engineering', name: 'Engineering', icon: '⚙️', description: 'Designs, optimization, TRL' },
  { slug: 'knowledge', name: 'Knowledge', icon: '📚', description: 'Knowledge graph, unknowns, ontology' },
  { slug: 'theory', name: 'Theory Ecology', icon: '🌐', description: 'Theories, fitness, predictions' },
  { slug: 'evolution', name: 'Evolution', icon: '🧬', description: 'Generations, candidates, regression' },
  { slug: 'certification', name: 'Certification', icon: '✓', description: 'Campaigns, evidence, readiness' },
  { slug: 'planetary', name: 'Planetary', icon: '🌍', description: 'Climate, energy, infrastructure' },
  { slug: 'civilization', name: 'Civilization', icon: '🏛️', description: 'Innovation, technology, Kardashev' },
  { slug: 'replay', name: 'Archaeology & Replay', icon: '⏪', description: 'Timeline, diffs, historical navigation' },
  { slug: 'observation-bus', name: 'Observation Bus', icon: '🔭', description: 'COB metrics, queues, subscribers, lineage' },
  { slug: 'constitutional-intelligence', name: 'Constitutional Intelligence', icon: '🧠', description: 'Health, patterns, anomalies, syntheses' },
  { slug: 'causal-explorer', name: 'Causal Explorer', icon: '🔗', description: 'Root cause tracing, risk matrix, causal graphs' },
  { slug: 'trend-observatory', name: 'Trend Observatory', icon: '📈', description: 'Long-term constitutional trajectories' },
  { slug: 'constitutional-advisor', name: 'Constitutional Advisor', icon: '💡', description: 'Live recommendations, decision support' },
  { slug: 'forecast-center', name: 'Forecast Center', icon: '🔮', description: 'Multi-horizon constitutional predictions' },
  { slug: 'scenario-lab', name: 'Scenario Lab', icon: '🧪', description: 'Simulate futures and compare outcomes' },
  { slug: 'risk-observatory', name: 'Risk Observatory', icon: '⚠️', description: 'Risk projections and mitigation' },
  { slug: 'preparedness-dashboard', name: 'Preparedness', icon: '🛡️', description: 'Readiness assessment across dimensions' },
  { slug: 'epistemic-atlas', name: 'Epistemic Atlas', icon: '🧭', description: 'Knowledge confidence, bias, assumptions' },
  { slug: 'unknown-landscape', name: 'Unknown Landscape', icon: '❓', description: 'First-class unknown tracking' },
  { slug: 'evidence-explorer', name: 'Evidence Explorer', icon: '🔍', description: 'Evidence → hypothesis → theory graph' },
  { slug: 'contradiction-observatory', name: 'Contradictions', icon: '⚡', description: 'Live contradiction map' },
  { slug: 'active-missions', name: 'Active Missions', icon: '🚀', description: 'Running, waiting, blocked, completed' },
  { slug: 'mission-galaxy', name: 'Mission Galaxy', icon: '🌌', description: 'Portfolio and domain distribution' },
  { slug: 'scientific-campaign', name: 'Scientific Campaign', icon: '📋', description: 'Campaign objectives and progress' },
  { slug: 'discovery-challenge-center', name: 'Challenge Center', icon: '🏆', description: 'Discovery challenge coordination' },
  { slug: 'portfolio-view', name: 'Portfolio View', icon: '📊', description: 'Scientific investment dashboard' },
  { slug: 'strategy-center', name: 'Strategy Center', icon: '🎯', description: 'Long-term roadmap, strategic priorities, bottlenecks' },
  { slug: 'capability-atlas', name: 'Capability Atlas', icon: '🗺️', description: 'Interactive capability dependency graph' },
  { slug: 'technology-roadmaps', name: 'Technology Roadmaps', icon: '🛤️', description: 'TRL, dependencies, timelines' },
  { slug: 'bottleneck-observatory', name: 'Bottleneck Observatory', icon: '🔴', description: 'Ranked strategic bottlenecks' },
  { slug: 'opportunity-observatory', name: 'Opportunity Observatory', icon: '💎', description: 'High-impact strategic directions' },
  { slug: 'civilization-control', name: 'Civilization Control', icon: '🌐', description: 'Global civilization state dashboard' },
  { slug: 'planetary-twin', name: 'Planetary Twin', icon: '🌍', description: 'Infrastructure, economy, education' },
  { slug: 'civilization-timeline', name: 'Civilization Timeline', icon: '⏳', description: 'Technology diffusion across centuries' },
  { slug: 'kardashev-dashboard', name: 'Kardashev Dashboard', icon: '⭐', description: 'Civilization capability tracking' },
  { slug: 'resilience-center', name: 'Resilience Center', icon: '🛡️', description: 'Vulnerabilities, recovery, adaptation' },
  { slug: 'future-galaxy', name: 'Future Galaxy', icon: '🌌', description: 'Every future as a node with probability, benefit, risk, fitness' },
  { slug: 'counterfactual-studio', name: 'Counterfactual Studio', icon: '🔀', description: 'Interactive what-if sandbox' },
  { slug: 'future-comparator', name: 'Future Comparator', icon: '⚖️', description: 'Compare futures across science, economy, resilience' },
  { slug: 'existential-risk-center', name: 'Existential Risk Center', icon: '☢️', description: 'Ranked existential, collapse, catastrophic risks' },
  { slug: 'meta-observatory', name: 'Meta-Observatory', icon: '👁️', description: 'Watching the watcher: observability coverage' },
  { slug: 'instrumentation-explorer', name: 'Instrumentation Explorer', icon: '📡', description: 'Proposed new telemetry, metrics, dashboards' },
  { slug: 'evolution-center', name: 'Evolution Center', icon: '🔄', description: 'Proposed changes → validation → certification → deployment' },
  { slug: 'constitutional-governance', name: 'Constitutional Governance', icon: '🏛️', description: 'Live governance of the Observatory itself' },
  { slug: 'observatory-genealogy', name: 'Observatory Genealogy', icon: '📜', description: 'Version history from v1 to current' },
  { slug: 'operations-command', name: 'Operations Command', icon: '🎮', description: 'Mission control for autonomous operations' },
  { slug: 'execution-timeline', name: 'Execution Timeline', icon: '⏱️', description: 'Plan → authorize → execute → verify → replay' },
  { slug: 'resource-command', name: 'Resource Command', icon: '📦', description: 'Live allocation of CPU, GPU, memory, energy' },
  { slug: 'safety-center', name: 'Safety Center', icon: '🛡️', description: 'Safety limits, interventions, halt capability' },
  { slug: 'federation-command', name: 'Federation Command', icon: '🌐', description: 'Connected observatories across civilization' },
  { slug: 'global-knowledge-map', name: 'Global Knowledge Map', icon: '🗺️', description: 'Civilization-scale knowledge graph' },
  { slug: 'discovery-federation', name: 'Discovery Federation', icon: '🔀', description: 'Discoveries propagating between nodes' },
  { slug: 'consensus-center', name: 'Consensus Center', icon: '🤝', description: 'Evidence-based constitutional consensus' },
  { slug: 'civilization-timeline-federation', name: 'Civ Timeline (Federation)', icon: '⏳', description: 'Federated civilization memory' },
]

export const ROOM_ICON_NAMES: Record<string, string> = {
  constitutional: 'shield',
  runtime: 'runtime',
  science: 'science',
  engineering: 'engineering',
  knowledge: 'knowledge',
  theory: 'theory',
  evolution: 'evolution',
  certification: 'certificate',
  planetary: 'planetary',
  civilization: 'civilization',
  replay: 'replay',
  'observation-bus': 'observation-bus',
  'constitutional-intelligence': 'constitutional-intelligence',
  'causal-explorer': 'causal-explorer',
  'trend-observatory': 'trend-observatory',
  'constitutional-advisor': 'constitutional-advisor',
  'forecast-center': 'forecast-center',
  'scenario-lab': 'scenario-lab',
  'risk-observatory': 'risk-observatory',
  'preparedness-dashboard': 'preparedness-dashboard',
  'epistemic-atlas': 'epistemic-atlas',
  'unknown-landscape': 'unknown-landscape',
  'evidence-explorer': 'evidence-explorer',
  'contradiction-observatory': 'contradiction-observatory',
  'active-missions': 'active-missions',
  'mission-galaxy': 'mission-galaxy',
  'scientific-campaign': 'scientific-campaign',
  'discovery-challenge-center': 'discovery-challenge-center',
  'portfolio-view': 'portfolio-view',
  'strategy-center': 'strategy-center',
  'capability-atlas': 'capability-atlas',
  'technology-roadmaps': 'technology-roadmaps',
  'bottleneck-observatory': 'bottleneck-observatory',
  'opportunity-observatory': 'opportunity-observatory',
  'civilization-control': 'civilization-control',
  'planetary-twin': 'planetary-twin',
  'civilization-timeline': 'civilization-timeline',
  'kardashev-dashboard': 'kardashev-dashboard',
  'resilience-center': 'resilience-center',
  'future-galaxy': 'future-galaxy',
  'counterfactual-studio': 'counterfactual-studio',
  'future-comparator': 'future-comparator',
  'existential-risk-center': 'existential-risk-center',
  'meta-observatory': 'meta-observatory',
  'instrumentation-explorer': 'instrumentation-explorer',
  'evolution-center': 'evolution-center',
  'constitutional-governance': 'constitutional-governance',
  'observatory-genealogy': 'observatory-genealogy',
  'operations-command': 'operations-command',
  'execution-timeline': 'execution-timeline',
  'resource-command': 'resource-command',
  'safety-center': 'safety-center',
  'federation-command': 'federation-command',
  'global-knowledge-map': 'global-knowledge-map',
  'discovery-federation': 'discovery-federation',
  'consensus-center': 'consensus-center',
  'civilization-timeline-federation': 'civilization-timeline-federation',
}

export function buildCommands(navigate: (slug: string) => void): CommandAction[] {
  const roomCommands: CommandAction[] = ROOMS.map((room) => ({
    id: `nav-${room.slug}`,
    label: `Open ${room.name}`,
    shortcut: undefined,
    action: () => navigate(room.slug),
    category: 'Navigation',
  }))

  return [
    ...roomCommands,
    { id: 'cmd-replay', label: 'Start Replay', action: () => navigate('replay'), category: 'Replay' },
    { id: 'cmd-compare', label: 'Compare Experiments', action: () => {}, category: 'Science' },
    { id: 'cmd-theory', label: 'Search Theory', action: () => {}, category: 'Knowledge' },
    { id: 'cmd-metrics', label: 'Show Runtime', action: () => navigate('runtime'), category: 'Runtime' },
    { id: 'cmd-export', label: 'Export Metrics', action: () => {}, category: 'Metrics' },
    { id: 'cmd-discovery', label: 'Jump to Discovery', action: () => {}, category: 'Science' },
    { id: 'cmd-challenge', label: 'Open Discovery Challenge', action: () => {}, category: 'Actions' },
    { id: 'cmd-hypothesis', label: 'Create Hypothesis', action: () => {}, category: 'Actions' },
    { id: 'cmd-experiment', label: 'Start Experiment', action: () => {}, category: 'Actions' },
  ]
}
