defmodule Tiannara.ASC.Implementation.Adapter.Elixir do
  @moduledoc """
  Elixir Language Adapter — converts ImplementationPlan into executable Elixir/Mix project.

  Generates:
  - lib/ (components, repositories, validators)
  - test/ (test files bound to TestContracts)
  - mix.exs (project configuration)
  - config/ (runtime configuration)
  - docs/ (README, OpenAPI spec)

  Every generated file includes metadata linking it back to:
  - Test contracts that validate it
  - Invariants that constrain it
  - Risks that threaten it
  """

  alias Tiannara.ASC.Implementation.Plan

  @doc """
  Generate complete Elixir project structure from implementation plan.
  """
  def generate_project(%Plan{} = plan, project_id) do
    sandbox_path = Path.join(["data", "asc_projects", project_id, "sandbox"])
    File.mkdir_p!(sandbox_path)

    # Generate project files
    generate_mix_exs(plan, sandbox_path)
    generate_config(sandbox_path)
    generate_readme(plan, sandbox_path)

    # Generate source files
    components = generate_components(plan, sandbox_path)
    repositories = generate_repositories(plan, sandbox_path)
    validators = generate_validators(plan, sandbox_path)

    # Generate test files
    tests = generate_tests(plan, sandbox_path)

    %{
      project_path: sandbox_path,
      components: components,
      repositories: repositories,
      validators: validators,
      tests: tests,
      total_files: length(components) + length(repositories) + length(validators) + length(tests) + 3
    }
  end

  @doc """
  Generate mix.exs project configuration.
  """
  def generate_mix_exs(%Plan{} = plan, sandbox_path) do
    project_name = String.downcase(String.replace(plan.project_id, "_", "-"))

    content = """
    defmodule #{Macro.camelize(project_name)}.MixProject do
      use Mix.Project

      def project do
        [
          app: :#{project_name},
          version: "0.1.0",
          elixir: "~> 1.14",
          start_permanent: Mix.env() == :prod,
          deps: deps()
        ]
      end

      def application do
        [
          extra_applications: [:logger]
        ]
      end

      defp deps do
        []
      end
    end
    """

    File.write!(Path.join(sandbox_path, "mix.exs"), content)
    "mix.exs"
  end

  @doc """
  Generate config directory with basic configuration.
  """
  def generate_config(sandbox_path) do
    config_dir = Path.join(sandbox_path, "config")
    File.mkdir_p!(config_dir)

    content = """
    import Config

    config :logger, level: :info
    """

    File.write!(Path.join(config_dir, "config.exs"), content)
    "config/config.exs"
  end

  @doc """
  Generate README.md with project overview.
  """
  def generate_readme(%Plan{} = plan, sandbox_path) do
    component_list = Enum.map_join(plan.components, "\n", &"  - #{&1.name}")

    content = """
    # #{plan.project_id}

    **Architecture Style**: #{plan.architecture_style}
    **Complexity Score**: #{plan.complexity_score}
    **Confidence**: #{plan.confidence}

    ## Components

    #{component_list}

    ## Generated by

    Tiannara ASC Implementation Planning Civilization (Phase 3)
    """

    File.write!(Path.join(sandbox_path, "README.md"), content)
    "README.md"
  end

  @doc """
  Generate component modules from plan.
  """
  def generate_components(%Plan{} = plan, sandbox_path) do
    lib_dir = Path.join(sandbox_path, "lib")
    File.mkdir_p!(lib_dir)

    Enum.map(plan.components, fn component ->
      module_name = Macro.camelize(component.name)
      file_name = "#{Macro.underscore(component.name)}.ex"
      file_path = Path.join(lib_dir, file_name)

      # Build function stubs from interfaces
      functions = Enum.map_join(component.interfaces, "\n\n", fn interface ->
        """
          @doc \"\"\"
          Interface: #{interface}.

          TODO: Implement based on test contracts and validation rules.
          \"\"\"
          @spec #{interface}(map()) :: {:ok, term()} | {:error, term()}
          def #{interface}(params) do
            {:error, :not_implemented}
          end
        """
      end)

      content = """
      defmodule #{module_name} do
        @moduledoc \"\"\"
        Component: #{component.name}

        Responsibilities:
        #{Enum.map_join(component.responsibilities, "\n  ", &"- #{&1}")}

        Dependencies:
        #{Enum.map_join(component.dependencies, "\n  ", &"- #{&1}")}

        Generated by Tiannara ASC Implementation Adapter (Phase 3.5)
        \"\"\"

      #{functions}
      end
      """

      File.write!(file_path, content)
      file_name
    end)
  end

  @doc """
  Generate repository modules for data persistence.
  """
  def generate_repositories(%Plan{} = plan, sandbox_path) do
    lib_dir = Path.join(sandbox_path, "lib")
    File.mkdir_p!(lib_dir)

    Enum.map(plan.components, fn component ->
      subject = String.replace(component.name, "Service", "")
      repo_name = "#{subject}Repository"
      module_name = Macro.camelize(repo_name)
      file_name = "#{Macro.underscore(repo_name)}.ex"
      file_path = Path.join(lib_dir, file_name)

      # Find storage model for this entity
      storage_model = Enum.find(plan.storage_models, fn model ->
        String.contains?(String.downcase(model.entity), String.downcase(subject))
      end)

      fields_doc = if storage_model do
        Enum.map_join(storage_model.fields, "\n  ", &"- #{&1.name}: #{&1.type}")
      else
        "- id: string"
      end

      content = """
      defmodule #{module_name} do
        @moduledoc \"\"\"
        Repository: #{repo_name}

        Entity: #{subject}

        Schema Fields:
        #{fields_doc}

        Generated by Tiannara ASC Implementation Adapter (Phase 3.5)
        \"\"\"

        @doc \"\"\"
        Get #{subject} by ID.
        \"\"\"
        @spec get(String.t()) :: {:ok, map()} | {:error, :not_found}
        def get(id) do
          {:error, :not_implemented}
        end

        @doc \"\"\"
        List all #{String.downcase(subject)} records.
        \"\"\"
        @spec list() :: {:ok, [map()]} | {:error, term()}
        def list() do
          {:error, :not_implemented}
        end

        @doc \"\"\"
        Create new #{String.downcase(subject)} record.
        \"\"\"
        @spec create(map()) :: {:ok, map()} | {:error, term()}
        def create(attrs) do
          {:error, :not_implemented}
        end

        @doc \"\"\"
        Update existing #{String.downcase(subject)} record.
        \"\"\"
        @spec update(String.t(), map()) :: {:ok, map()} | {:error, term()}
        def update(id, attrs) do
          {:error, :not_implemented}
        end

        @doc \"\"\"
        Delete #{String.downcase(subject)} record.
        \"\"\"
        @spec delete(String.t()) :: {:ok, map()} | {:error, term()}
        def delete(id) do
          {:error, :not_implemented}
        end
      end
      """

      File.write!(file_path, content)
      file_name
    end)
  end

  @doc """
  Generate validator modules from validation rules.
  """
  def generate_validators(%Plan{} = plan, sandbox_path) do
    lib_dir = Path.join(sandbox_path, "lib")
    File.mkdir_p!(lib_dir)

    Enum.map(plan.components, fn component ->
      subject = String.replace(component.name, "Service", "")
      validator_name = "#{subject}Validator"
      module_name = Macro.camelize(validator_name)
      file_name = "#{Macro.underscore(validator_name)}.ex"
      file_path = Path.join(lib_dir, file_name)

      # Find validation rules for this component
      rules = Enum.filter(plan.validation_rules, fn rule ->
        # Match rules to components heuristically
        String.contains?(rule.implementation || "", String.downcase(subject))
      end)

      rules_doc = if rules != [] do
        Enum.map_join(rules, "\n  ", &"- #{&1.rule_type}: #{&1.implementation}")
      else
        "- No specific validation rules defined"
      end

      content = """
      defmodule #{module_name} do
        @moduledoc \"\"\"
        Validator: #{validator_name}

        Entity: #{subject}

        Validation Rules:
        #{rules_doc}

        Generated by Tiannara ASC Implementation Adapter (Phase 3.5)
        \"\"\"

        @doc \"\"\"
        Validate #{subject} attributes.
        \"\"\"
        @spec validate(map()) :: {:ok, map()} | {:error, list()}
        def validate(attrs) do
          errors = []

          # TODO: Implement validation rules from ImplementationPlan
          # Current rules: #{length(rules)}

          if errors == [] do
            {:ok, attrs}
          else
            {:error, errors}
          end
        end
      end
      """

      File.write!(file_path, content)
      file_name
    end)
  end

  @doc """
  Generate test files bound to TestContracts.
  """
  def generate_tests(%Plan{} = plan, sandbox_path) do
    test_dir = Path.join(sandbox_path, "test")
    File.mkdir_p!(test_dir)

    # Generate test file for each component
    Enum.map(plan.components, fn component ->
      test_name = "#{Macro.underscore(component.name)}_test.exs"
      test_path = Path.join(test_dir, test_name)

      module_name = Macro.camelize(component.name)

      test_cases = Enum.map_join(component.interfaces, "\n\n", fn interface ->
        """
          test \"#{interface} returns not_implemented\" do
            # TODO: Replace with actual test based on TestContract
            assert {:error, :not_implemented} = #{module_name}.#{interface}(%{})
          end
        """
      end)

      content = """
      defmodule #{module_name}Test do
        use ExUnit.Case
        doctest #{module_name}

        alias #{module_name}

        describe \"#{component.name}\" do
          #{test_cases}
        end
      end
      """

      File.write!(test_path, content)
      test_name
    end)
  end
end
