defmodule ObservatoryApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :observatory_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_observatory_api_key",
    signing_salt: "YQ7+P00I",
    same_site: "Lax"
  ]

  socket "/ws", ObservatoryApiWeb.ObservatorySocket,
    websocket: [connect_info: [:peer_data, :x_headers, :uri]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :observatory_api,
    gzip: not code_reloading?,
    only: ObservatoryApiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :observatory_api
  end

  plug CORSPlug, origin: Application.compile_env(:observatory_api, :cors_origins, "*")

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ObservatoryApiWeb.Router
end
