defmodule Tiannara.ToolForge.ToolBuilder do
  use GenServer
  require Logger

  alias Tiannara.ToolForge.Domain.{ToolSpecification, GeneratedTool}

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @doc "Builds a tool from a specification. Returns {:ok, GeneratedTool.t()} or {:error, reason}."
  def build(%ToolSpecification{} = spec) do
    GenServer.call(__MODULE__, {:build, spec}, 60_000)
  end

  @doc "Builds a tool and writes it to disk."
  def build_to_disk(%ToolSpecification{} = spec, output_dir) do
    GenServer.call(__MODULE__, {:build_to_disk, spec, output_dir}, 60_000)
  end

  @impl true
  def init(_opts) do
    {:ok, %{builds_completed: 0, builds_failed: 0}}
  end

  @impl true
  def handle_call({:build, spec}, _from, state) do
    case do_build(spec) do
      {:ok, tool} ->
        {:reply, {:ok, tool}, %{state | builds_completed: state.builds_completed + 1}}
      {:error, reason} ->
        {:reply, {:error, reason}, %{state | builds_failed: state.builds_failed + 1}}
    end
  end

  @impl true
  def handle_call({:build_to_disk, spec, output_dir}, _from, state) do
    case do_build(spec) do
      {:ok, tool} ->
        File.mkdir_p!(output_dir)
        Enum.each(tool.source_files, fn {filename, content} ->
          path = Path.join(output_dir, filename)
          File.mkdir_p!(Path.dirname(path))
          File.write!(path, content)
        end)
        Enum.each(tool.test_files, fn {filename, content} ->
          path = Path.join([output_dir, "test", filename])
          File.mkdir_p!(Path.dirname(path))
          File.write!(path, content)
        end)
        {:reply, {:ok, tool}, %{state | builds_completed: state.builds_completed + 1}}
      {:error, reason} ->
        {:reply, {:error, reason}, %{state | builds_failed: state.builds_failed + 1}}
    end
  end

  @impl true
  def handle_info(_, state), do: {:noreply, state}

  defp do_build(%ToolSpecification{language: :elixir} = spec), do: build_elixir_tool(spec)
  defp do_build(%ToolSpecification{language: :python} = spec), do: build_python_tool(spec)
  defp do_build(%ToolSpecification{language: _} = spec), do: build_generic_tool(spec)

  defp build_elixir_tool(%ToolSpecification{} = spec) do
    module_name = Macro.camelize(spec.name)

    main_template = """
    defmodule Tiannara.Tools.#{module_name} do
      @moduledoc #{inspect(spec.description)} (Auto-generated by Tiannara.ToolForge, Specification: #{spec.id})
      use GenServer
      require Logger

      def start_link(opts \\\\ []) do
        GenServer.start_link(__MODULE__, opts, name: __MODULE__)
      end

      def execute(input) do
        GenServer.call(__MODULE__, {:execute, input})
      end

      def health do
        GenServer.call(__MODULE__, :health)
      end

      def metrics do
        GenServer.call(__MODULE__, :metrics)
      end

      @impl true
      def init(_opts) do
        {:ok, %{started_at: DateTime.utc_now(), executions: 0, errors: 0}}
      end

      @impl true
      def handle_call({:execute, input}, _from, state) do
        try do
          result = do_execute(input)
          {:reply, {:ok, result}, %{state | executions: state.executions + 1}}
        rescue
          e ->
            Logger.error("Tiannara.Tools.#{module_name}: execution failed: __INSPECT_E__")
            {:reply, {:error, e}, %{state | errors: state.errors + 1}}
        end
      end

      @impl true
      def handle_call(:health, _from, state) do
        {:reply, %{healthy: true, executions: state.executions, errors: state.errors}, state}
      end

      @impl true
      def handle_call(:metrics, _from, state) do
        {:reply, %{
          executions: state.executions,
          errors: state.errors,
          uptime_seconds: DateTime.diff(DateTime.utc_now(), state.started_at, :second)
        }, state}
      end

      @impl true
      def handle_info(_, state), do: {:noreply, state}

      defp do_execute(input) do
        {:error, {:not_implemented, input}}
      end
    end
    """

    inspect_e_replacement = "#{?#}{inspect(e)}"
    main_module = String.replace(main_template, "__INSPECT_E__", inspect_e_replacement)

    test_module = """
    defmodule Tiannara.Tools.#{module_name}Test do
      use ExUnit.Case, async: true

      alias Tiannara.Tools.#{module_name}

      setup do
        case #{module_name}.start_link([]) do
          {:ok, pid} -> on_exit(fn -> if Process.alive?(pid), do: GenServer.stop(pid) end)
          {:error, {:already_started, _}} -> :ok
        end
        :ok
      end

      test "health check responds" do
        health = #{module_name}.health()
        assert health.healthy == true
      end

      test "execute returns result" do
        assert {:ok, _} = #{module_name}.execute(%{test: true})
      end

      test "metrics tracks executions" do
        #{module_name}.execute(%{test: 1})
        metrics = #{module_name}.metrics()
        assert metrics.executions >= 1
      end
    end
    """

    tool = GeneratedTool.new(%{
      spec_id: spec.id,
      name: spec.name,
      language: :elixir,
      source_files: %{"lib/tiannara/tools/#{spec.name}.ex" => main_module},
      test_files: %{"#{spec.name}_test.exs" => test_module},
      entry_point: "Tiannara.Tools.#{module_name}",
      build_instructions: "Add to supervision tree: {Tiannara.Tools.#{module_name}, []}",
      generation_metadata: %{
        generator: :tool_forge,
        spec_id: spec.id,
        architecture: spec.architecture.pattern
      }
    })

    {:ok, tool}
  end

  defp build_python_tool(%ToolSpecification{} = spec) do
    main_file = """
    #{spec.description}

    Auto-generated by Tiannara.ToolForge.
    Specification: #{spec.id}
    Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}
    from fastapi import FastAPI
    from pydantic import BaseModel
    from typing import Optional, Dict, Any
    import time

    app = FastAPI(
        title="#{spec.name}",
        description="#{spec.description}",
        version="1.0.0"
    )

    START_TIME = time.time()
    EXECUTIONS = 0
    ERRORS = 0


    class ExecuteRequest(BaseModel):
        input: Dict[str, Any] = {}


    class ExecuteResponse(BaseModel):
        result: Any
        execution_time_ms: float


    @app.get("/health")
    async def health():
        return {
            "healthy": True,
            "uptime_seconds": time.time() - START_TIME,
            "executions": EXECUTIONS,
            "errors": ERRORS
        }


    @app.get("/metrics")
    async def metrics():
        return {
            "executions": EXECUTIONS,
            "errors": ERRORS,
            "uptime_seconds": time.time() - START_TIME
        }


    @app.post("/execute", response_model=ExecuteResponse)
    async def execute(request: ExecuteRequest):
        global EXECUTIONS, ERRORS
        start = time.time()
        try:
            result = do_execute(request.input)
            EXECUTIONS += 1
            return ExecuteResponse(
                result=result,
                execution_time_ms=(time.time() - start) * 1000
            )
        except Exception as e:
            ERRORS += 1
            return ExecuteResponse(result={"error": str(e)}, execution_time_ms=(time.time() - start) * 1000)


    def do_execute(input_data: Dict[str, Any]) -> Any:
        # TODO: Implementation generated from specification.
        return {"status": "implemented", "input": input_data}


    if __name__ == "__main__":
        import uvicorn
        uvicorn.run(app, host="0.0.0.0", port=8100)
    """

    requirements = """
    fastapi>=0.100.0
    uvicorn>=0.23.0
    pydantic>=2.0.0
    """

    dockerfile = """
    FROM python:3.11-slim
    WORKDIR /app
    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt
    COPY . .
    EXPOSE 8100
    CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100"]
    """

    tool = GeneratedTool.new(%{
      spec_id: spec.id,
      name: spec.name,
      language: :python,
      source_files: %{
        "main.py" => main_file,
        "requirements.txt" => requirements,
        "Dockerfile" => dockerfile
      },
      test_files: %{},
      entry_point: "main:app",
      build_instructions: "docker build -t #{spec.name} . && docker run -p 8100:8100 #{spec.name}",
      generation_metadata: %{
        generator: :tool_forge,
        spec_id: spec.id,
        architecture: spec.architecture.pattern
      }
    })

    {:ok, tool}
  end

  defp build_generic_tool(%ToolSpecification{} = spec) do
    spec_doc = """
    # Tool Specification: #{spec.name}

    #{spec.description}

    ## Language: #{spec.language}
    ## Architecture: #{spec.architecture.pattern}

    ## Interfaces
    #{Enum.map_join(spec.interfaces, "\n", fn i -> "- `#{i.name}`: #{i.description}" end)}

    ## Dependencies
    #{Enum.map_join(spec.dependencies, "\n", fn d -> "- #{d.name} #{d.version}" end)}

    ## Security Requirements
    - Sandboxed: #{spec.security_requirements.sandboxed}
    - Max execution time: #{spec.security_requirements.max_execution_time_ms}ms
    - Resource limits: #{spec.security_requirements.resource_limits}

    ## Verification Plan
    #{Enum.map_join(spec.verification_plan.acceptance_criteria, "\n", fn c -> "- [ ] #{c}" end)}

    ## Evolution Strategy
    #{spec.evolution_strategy.description}
    """

    tool = GeneratedTool.new(%{
      spec_id: spec.id,
      name: spec.name,
      language: spec.language,
      source_files: %{"SPECIFICATION.md" => spec_doc},
      test_files: %{},
      entry_point: nil,
      build_instructions: "Implement according to specification",
      generation_metadata: %{generator: :tool_forge, spec_id: spec.id}
    })

    {:ok, tool}
  end
end
