defmodule Tiannara.ASC.ProjectWorld.TestContract do
  @moduledoc """
  A test contract bridges a formal requirement to an executable test specification.

  TestContracts are generated by the **Testing Civilization BEFORE code is written**.
  This ensures "what success looks like" is formally defined before the
  Implementation Civilization writes any function bodies.

  ## Contract Types

  - `:property`     — StreamData property test for an Invariant
  - `:unit`         — ExUnit unit test for a Capability
  - `:integration`  — Cross-boundary test for a multi-step Capability
  - `:contract`     — API schema/contract validation
  - `:load`         — Performance assertion derived from a Constraint
  - `:security`     — Adversarial scenario derived from a Risk

  ## Lifecycle

  Testing.Civilization → ProjectWorld.test_contracts →
  Implementation.Civilization (reads contracts as function specifications) →
  Crucible (executes contracts as validation criteria) →
  Observatory (records test_effectiveness, bug_discovery_rate)
  """

  @derive Jason.Encoder

  defstruct [
    :id,
    :type,               # :property | :unit | :integration | :contract | :load | :security
    :source_ref,         # ID of the invariant / capability / constraint / risk it covers
    :source_type,        # :invariant | :capability | :constraint | :risk
    :description,
    :test_module_name,   # e.g. "AccountServiceTest"
    :test_function_name, # e.g. "test balance cannot go below zero"
    :property_spec,      # StreamData generator description (for :property and :load types)
    :expected_behavior,  # human-readable expectation
    :priority,           # :critical | :high | :medium | :low
    :coverage_dimension, # :invariants | :capabilities | :integration | :performance | :security
    :status,             # :pending | :generated | :passing | :failing
    tags: []
  ]

  @type contract_type :: :property | :unit | :integration | :contract | :load | :security
  @type priority :: :critical | :high | :medium | :low
  @type status :: :pending | :generated | :passing | :failing

  @type t :: %__MODULE__{
    id: String.t(),
    type: contract_type(),
    source_ref: String.t(),
    source_type: :invariant | :capability | :constraint | :risk,
    description: String.t(),
    test_module_name: String.t() | nil,
    test_function_name: String.t() | nil,
    property_spec: map() | nil,
    expected_behavior: String.t(),
    priority: priority(),
    coverage_dimension: atom(),
    status: status(),
    tags: [String.t()]
  }

  @spec new(contract_type(), String.t(), atom(), String.t(), keyword()) :: t()
  def new(type, source_ref, source_type, description, opts \\ []) do
    %__MODULE__{
      id: "tc_#{:erlang.unique_integer([:positive, :monotonic])}",
      type: type,
      source_ref: source_ref,
      source_type: source_type,
      description: description,
      test_module_name: Keyword.get(opts, :test_module_name),
      test_function_name: Keyword.get(opts, :test_function_name),
      property_spec: Keyword.get(opts, :property_spec),
      expected_behavior: Keyword.get(opts, :expected_behavior, description),
      priority: Keyword.get(opts, :priority, :high),
      coverage_dimension: Keyword.get(opts, :coverage_dimension, :capabilities),
      status: :pending,
      tags: Keyword.get(opts, :tags, [])
    }
  end

  @doc "True if this contract must pass for the project to reach the Crucible phase."
  @spec blocking?(t()) :: boolean()
  def blocking?(%__MODULE__{priority: p}), do: p in [:critical, :high]
end
