defmodule Tiannara.HAI.Collaboration.ScientificNotebook do
  alias Tiannara.Discovery.Discovery
  alias Tiannara.Discovery.DiscoveryLineage

  @spec generate(Discovery.t()) :: map()
  def generate(%Discovery{} = disc) do
    %{
      id: "notebook_#{disc.id}",
      discovery_id: disc.id,
      title: "Scientific Notebook: #{disc.question}",
      sections: [
        build_introduction(disc),
        build_methodology(disc),
        build_results(disc),
        build_analysis(disc),
        build_conclusions(disc),
        build_reproducibility_guide(disc),
        build_appendix(disc)
      ],
      metadata: %{
        generated_at: DateTime.utc_now(),
        discovery_status: disc.status,
        confidence: disc.confidence,
        uncertainty: disc.uncertainty,
        lineage_depth: Discovery.lineage_depth(disc),
        total_evidence: length(disc.evidence)
      }
    }
  end

  @spec render(map()) :: String.t()
  def render(notebook) do
    sections_text =
      Enum.map_join(notebook.sections, "\n\n", fn section ->
        """
        ## #{section.title}

        #{section.content}
        """
      end)

    """
    # #{notebook.title}

    Generated: #{notebook.metadata.generated_at}
    Status: #{notebook.metadata.discovery_status}
    Confidence: #{Float.round(notebook.metadata.confidence, 3)} +/- #{Float.round(notebook.metadata.uncertainty, 3)}

    ---

    #{sections_text}

    ---
    *This notebook was automatically generated by Tiannara's Scientific Notebook system.
    All steps are reproducible. All assumptions are documented. All evidence is cited.*
    """
  end

  defp build_introduction(%Discovery{} = disc) do
    %{
      title: "1. Introduction",
      content: """
      ### Research Question
      #{disc.question}

      ### Knowledge Gap
      #{if disc.gap, do: disc.gap.description, else: "Not specified"}

      ### Domain
      #{if disc.gap, do: disc.gap.domain, else: :unknown}

      ### Severity
      #{if disc.gap, do: disc.gap.severity, else: :unknown}

      ### Motivation
      This investigation was initiated by the Autonomous Discovery Engine
      based on an epistemic integrity report indicating a knowledge gap
      with estimated impact #{if disc.gap, do: Float.round(disc.gap.estimated_impact, 2), else: "N/A"}.
      """
    }
  end

  defp build_methodology(%Discovery{} = disc) do
    hypotheses_text =
      Enum.map_join(disc.hypotheses, "\n", fn hyp ->
        "- **#{hyp.statement}** (prior: #{Float.round(hyp.prior, 3)}, EIG: #{Float.round(hyp.expected_information_gain, 3)})"
      end)

    experiments_text =
      Enum.map_join(disc.experiments, "\n", fn exp ->
        "- #{exp.type}: #{exp.id} (EIG: #{Float.round(exp.expected_information_gain, 3)})"
      end)

    %{
      title: "2. Methodology",
      content: """
      ### Hypotheses Generated (#{length(disc.hypotheses)})
      #{hypotheses_text}

      ### Predictions Derived (#{length(disc.predictions)})
      #{length(disc.predictions)} falsifiable predictions were derived from the hypotheses.

      ### Experiments Designed (#{length(disc.experiments)})
      #{experiments_text}

      ### Evidence Collection Protocol
      Evidence was collected through the Workflow Engine (Phase 2) and
      integrated through the Knowledge Coordinator (Phase 3) using
      Bayesian evidence fusion.
      """
    }
  end

  defp build_results(%Discovery{} = disc) do
    evidence_text =
      if disc.evidence == [] do
        "No evidence collected."
      else
        Enum.map_join(disc.evidence, "\n", fn result ->
          "- #{result.outcome}: experiment #{result.experiment_id} " <>
          "(confidence delta: #{Float.round(result.confidence_delta, 3)}, " <>
          "#{length(result.evidence)} evidence items)"
        end)
      end

    %{
      title: "3. Results",
      content: """
      ### Evidence Collected (#{length(disc.evidence)} items)
      #{evidence_text}

      ### Confidence Evolution
      - Initial confidence: 0.000
      - Final confidence: #{Float.round(disc.confidence, 3)}
      - Final uncertainty: #{Float.round(disc.uncertainty, 3)}
      """
    }
  end

  defp build_analysis(%Discovery{} = disc) do
    %{
      title: "4. Analysis",
      content: """
      ### Outcome Assessment
      #{if disc.conclusion, do: Map.get(disc.conclusion, :summary, "Conclusion reached."), else: "Analysis pending."}

      ### Assumptions
      - The knowledge gap is genuine (not an artifact of incomplete data)
      - The experimental methodology is sound
      - Evidence collection is unbiased
      #{if disc.gap && disc.gap.source == :contradiction, do: "- The contradiction is not due to measurement error", else: ""}

      ### Limitations
      - #{if length(disc.evidence) < 3, do: "Limited evidence base (#{length(disc.evidence)} items)", else: "Evidence base is adequate"}
      - #{if disc.uncertainty > 0.4, do: "High residual uncertainty (#{Float.round(disc.uncertainty, 2)})", else: "Uncertainty is within acceptable bounds"}
      - Independent replication not yet performed
      """
    }
  end

  defp build_conclusions(%Discovery{} = disc) do
    %{
      title: "5. Conclusions",
      content: """
      ### Status: #{disc.status}

      ### Confidence: #{Float.round(disc.confidence, 3)} +/- #{Float.round(disc.uncertainty, 3)}

      ### Conclusion
      #{if disc.conclusion, do: Map.get(disc.conclusion, :summary, "Conclusion reached."), else: "No conclusion reached yet."}

      ### Future Work
      - Independent replication of key findings
      #{if disc.uncertainty > 0.3, do: "- Additional experiments to reduce uncertainty below 0.3", else: ""}
      - Cross-domain validation of conclusions
      """
    }
  end

  defp build_reproducibility_guide(%Discovery{} = disc) do
    %{
      title: "6. Reproducibility Guide",
      content: """
      ### How to Reproduce This Discovery

      1. **Input**: Knowledge gap with domain=#{if disc.gap, do: disc.gap.domain, else: :unknown},
         severity=#{if disc.gap, do: disc.gap.severity, else: :unknown}

      2. **Hypothesis Generation**: Run `HypothesisGenerator.generate(gap)` with the same gap parameters.

      3. **Prediction Derivation**: Run `PredictionEngine.generate(hypothesis)` for each hypothesis.

      4. **Experiment Design**: Run `ExperimentPlanner.plan(hypothesis, predictions)` for each hypothesis.

      5. **Evidence Collection**: Execute experiments via WorkflowEngine with the same parameters.

      6. **Evidence Integration**: Run `EvidenceIntegrator.process_results(discovery, results)`.

      ### Determinism Note
      Hypothesis generation uses randomized IDs. The structural content
      (statements, priors, causal models) is deterministic given the same input gap.
      """
    }
  end

  defp build_appendix(%Discovery{} = disc) do
    %{
      title: "7. Appendix",
      content: """
      ### Lineage
      #{length(disc.lineage)} lineage events recorded.

      ### Workflow IDs
      #{if disc.workflow_ids == [], do: "None", else: Enum.join(disc.workflow_ids, ", ")}

      ### Discovery Score
      Composite: #{Float.round(Tiannara.Discovery.DiscoveryScore.composite(disc.score), 4)}

      ### System Versions
      - Discovery Engine: Phase 4.1
      - Engineering Layer: Phase 4.2
      - Simulation Sandbox: Phase 4.3
      - Human Interface: Phase 4.4
      """
    }
  end
end
