defmodule Tiannara.Research.Hypothesis do
  @moduledoc """
  A research hypothesis generated by the Research Director in response
  to a Sentinel epistemic event. Contains the proposed explanation,
  predicted outcomes, and the experiment designed to test it.
  """

  defstruct [
    :id,
    :event_id,
    :question,
    :proposed_explanation,
    :predicted_outcome,
    :experiment_id,
    :confidence,
    :expected_information_gain,
    :status,
    :created_at,
    :domain,
    evidence: [],
    alternative_hypotheses: [],
    metadata: %{}
  ]

  @type status :: :proposed | :approved | :testing | :confirmed | :refuted | :inconclusive
  @type t :: %__MODULE__{
          id: String.t(),
          event_id: String.t(),
          question: String.t(),
          proposed_explanation: String.t(),
          predicted_outcome: String.t(),
          experiment_id: String.t() | nil,
          confidence: float(),
          expected_information_gain: float(),
          status: status(),
          created_at: DateTime.t(),
          domain: atom(),
          evidence: list(map()),
          alternative_hypotheses: list(String.t()),
          metadata: map()
        }

  def new(event_id, question, explanation, opts \\ []) do
    %__MODULE__{
      id: "hyp_#{System.unique_integer([:positive])}",
      event_id: event_id,
      question: question,
      proposed_explanation: explanation,
      predicted_outcome: Map.get(opts, :predicted_outcome, "TBD"),
      confidence: Map.get(opts, :confidence, 0.5),
      expected_information_gain: Map.get(opts, :expected_information_gain, 0.0),
      status: :proposed,
      created_at: DateTime.utc_now(),
      domain: Map.get(opts, :domain, :general),
      evidence: Map.get(opts, :evidence, []),
      alternative_hypotheses: Map.get(opts, :alternatives, [])
    }
  end
end
