defmodule Tiannara.ASC.APIEvolution.Generator do
  @moduledoc """
  Autonomous API Generator — infers API endpoints, schemas, and contracts from ImplementationPlan.

  Flow:
    Implementation Plan
    ↓
    Endpoints inferred from capabilities/interfaces
    ↓
    Schemas inferred from storage models/validation rules
    ↓
    OpenAPI spec generated
    ↓
    Persisted to project history

  This enables future law discovery around:
  - Architecture Style → API Complexity
  - Capability Diversity → Endpoint Count
  - Validation Density → Schema Richness
  """

  alias Tiannara.ASC.Implementation.Plan

  @doc """
  Generate OpenAPI specification from implementation plan (map version).
  """
  def generate_openapi_from_map(plan_map, project_id) do
    openapi_spec = build_openapi_spec_from_map(plan_map)

    # Persist to project directory
    dir = Path.join(["data", "asc_projects", project_id])
    File.mkdir_p!(dir)

    file_path = Path.join(dir, "openapi.json")
    json = Jason.encode!(openapi_spec, pretty: true)
    File.write!(file_path, json)

    %{
      file_path: file_path,
      endpoint_count: length(Map.get(openapi_spec, "paths", %{})),
      schema_count: map_size(Map.get(openapi_spec, "components", %{}) |> Map.get("schemas", %{}))
    }
  end

  defp build_openapi_spec_from_map(plan_map) do
    interfaces = Map.get(plan_map, "interfaces", [])
    storage_models = Map.get(plan_map, "storage_models", [])
    
    paths = generate_paths_from_map(interfaces)
    schemas = generate_schemas_from_map(storage_models)

    %{
      "openapi" => "3.0.0",
      "info" => %{
        "title" => "#{Map.get(plan_map, "project_id", "unknown")} API",
        "version" => "0.1.0",
        "description" => "Auto-generated by Tiannara ASC API Evolution Generator"
      },
      "paths" => paths,
      "components" => %{
        "schemas" => schemas
      }
    }
  end

  defp generate_paths_from_map(interfaces) do
    Enum.reduce(interfaces, %{}, fn interface, acc ->
      path = Map.get(interface, "path", "/")
      method = String.downcase(Map.get(interface, "method", "get"))
      name = Map.get(interface, "name", "unknown")

      operation = %{
        "summary" => name,
        "operationId" => name,
        "responses" => %{
          "200" => %{
            "description" => "Successful operation"
          },
          "400" => %{
            "description" => "Bad request"
          }
        }
      }

      Map.update(acc, path, %{method => operation}, fn existing ->
        Map.put(existing, method, operation)
      end)
    end)
  end

  defp generate_schemas_from_map(storage_models) do
    Enum.reduce(storage_models, %{}, fn model, acc ->
      entity = Map.get(model, "entity", "unknown")
      schema_name = Macro.camelize(entity)
      fields = Map.get(model, "fields", [])

      properties = Enum.reduce(fields, %{}, fn field, props ->
        field_name = Map.get(field, "name", "unknown")
        field_type = Map.get(field, "type", "string")
        
        Map.put(props, field_name, %{
          "type" => elixir_type_to_openapi(field_type)
        })
      end)

      schema = %{
        "type" => "object",
        "properties" => properties
      }

      Map.put(acc, schema_name, schema)
    end)
  end

  @doc """
  Generate OpenAPI specification from implementation plan struct.
  """
  def generate_openapi(%Plan{} = plan, project_id) do
    openapi_spec = build_openapi_spec(plan)

    # Persist to project directory
    dir = Path.join(["data", "asc_projects", project_id])
    File.mkdir_p!(dir)

    file_path = Path.join(dir, "openapi.json")
    json = Jason.encode!(openapi_spec, pretty: true)
    File.write!(file_path, json)

    %{
      file_path: file_path,
      endpoint_count: length(openapi_spec["paths"]),
      schema_count: map_size(openapi_spec["components"]["schemas"])
    }
  end

  defp build_openapi_spec(%Plan{} = plan) do
    paths = generate_paths(plan.interfaces)
    schemas = generate_schemas(plan.storage_models)

    %{
      "openapi" => "3.0.0",
      "info" => %{
        "title" => "#{plan.project_id} API",
        "version" => "0.1.0",
        "description" => "Auto-generated by Tiannara ASC API Evolution Generator"
      },
      "paths" => paths,
      "components" => %{
        "schemas" => schemas
      }
    }
  end

  defp generate_paths(interfaces) do
    Enum.reduce(interfaces, %{}, fn interface, acc ->
      path = interface.path || "/"
      method = String.downcase(interface.method || "get")

      operation = %{
        "summary" => interface.name,
        "operationId" => interface.name,
        "requestBody" => generate_request_body(interface),
        "responses" => %{
          "200" => %{
            "description" => "Successful operation",
            "content" => %{
              "application/json" => %{
                "schema" => %{"type" => "object"}
              }
            }
          },
          "400" => %{
            "description" => "Bad request"
          },
          "500" => %{
            "description" => "Internal server error"
          }
        }
      }

      Map.update(acc, path, %{method => operation}, fn existing ->
        Map.put(existing, method, operation)
      end)
    end)
  end

  defp generate_request_body(interface) do
    if interface.input_schema && map_size(interface.input_schema) > 0 do
      %{
        "required" => true,
        "content" => %{
          "application/json" => %{
            "schema" => %{"type" => "object"}
          }
        }
      }
    else
      nil
    end
  end

  defp generate_schemas(storage_models) do
    Enum.reduce(storage_models, %{}, fn model, acc ->
      schema_name = Macro.camelize(model.entity)

      properties = Enum.reduce(model.fields, %{}, fn field, props ->
        Map.put(props, field.name, %{
          "type" => elixir_type_to_openapi(field.type)
        })
      end)

      required_fields = Enum.filter(model.fields, & &1[:primary_key])
                        |> Enum.map(& &1.name)

      schema = %{
        "type" => "object",
        "properties" => properties,
        "required" => required_fields
      }

      Map.put(acc, schema_name, schema)
    end)
  end

  defp elixir_type_to_openapi(type) do
    case String.downcase(type) do
      "string" -> "string"
      "integer" -> "integer"
      "float" -> "number"
      "boolean" -> "boolean"
      "datetime" -> "string"
      _ -> "string"
    end
  end
end
