defmodule Tiannara.ASC.Research.TelemetrySnapshot do
  @moduledoc """
  Phase 6.1: Captures the empirical state of the ASC knowledge base.
  Used to measure the actual, non-simulated delta generated by research programs.
  """
  
  alias Tiannara.ASC.Laws.Registry
  alias Tiannara.ASC.Crucible.{RepairLibrary, TransferEcology}

  def take do
    metrics = TransferEcology.get_metrics()
    
    %{
      laws_count: length(Registry.all()),
      canonical_count: length(Registry.get_laws_by_status(:canonical_principle)),
      refuted_count: length(Registry.get_laws_by_status(:refuted)),
      patterns_count: length(RepairLibrary.get_all_patterns()),
      transfer_events: length(TransferEcology.get_all_events()),
      matrix_cells_populated: Map.get(metrics, :matrix_cells_populated, 0),
      domain_entropy: Map.get(metrics, :domain_entropy, 0.0),
      total_utility: calculate_total_utility(),
      timestamp: System.system_time(:millisecond)
    }
  end

  @doc """
  Calculates the empirical difference between two states of the civilization.
  Includes advanced Phase 7 metrics: Information Gain and Law Impact.
  """
  def calculate_delta(before_snap, after_snap) do
    # 1. Coverage Gain: New cells populated
    coverage_gain = max(0, after_snap.matrix_cells_populated - before_snap.matrix_cells_populated) * 10.0
    
    # 2. Entropy Gain: Increases in domain entropy
    entropy_gain = max(0.0, after_snap.domain_entropy - before_snap.domain_entropy) * 50.0
    
    # 3. Surprise Gain: Architecture hook (defaults to 0 for now)
    surprise_gain = 0.0
    
    # 4. Law Impact Gain: Refutations and Canonical Promotions
    demotions = max(0, after_snap.refuted_count - before_snap.refuted_count)
    promotions = max(0, after_snap.canonical_count - before_snap.canonical_count)
    law_impact_gain = (demotions * 300.0) + (promotions * 100.0)
    
    information_gain = coverage_gain + entropy_gain + surprise_gain
    
    %{
      laws_generated: max(0, after_snap.laws_count - before_snap.laws_count),
      canonical_generated: max(0, after_snap.canonical_count - before_snap.canonical_count),
      patterns_discovered: max(0, after_snap.patterns_count - before_snap.patterns_count),
      events_recorded: max(0, after_snap.transfer_events - before_snap.transfer_events),
      utility_generated: max(0.0, after_snap.total_utility - before_snap.total_utility),
      compute_consumed: max(1, trunc((after_snap.timestamp - before_snap.timestamp) / 1000)),
      
      # Phase 7 Meta-Science metrics
      coverage_gain: coverage_gain,
      entropy_gain: entropy_gain,
      surprise_gain: surprise_gain,
      information_gain: information_gain,
      law_impact_gain: law_impact_gain
    }
  end

  defp calculate_total_utility do
    Registry.all()
    |> Enum.reduce(0.0, fn law, acc -> acc + (Map.get(law, :utility_score, 0.0) || 0.0) end)
  end
end
