defmodule TiannaraRuntime.Mathematics.AlgebraKernel do
  @moduledoc """
  Deterministic, terminating elementary algebra normalizer.

  This kernel proves only equivalences generated by its explicit rules.
  It does not use numerical sampling as proof.
  """

  def normalize({:op, :add, [a, b]}) do
    {:ok, sort_terms([normalize_expr(a), normalize_expr(b)]) |> add_expr()}
  end

  def normalize({:op, :multiply, [a, b]}) do
    {:ok, sort_terms([normalize_expr(a), normalize_expr(b)]) |> multiply_expr()}
  end

  def normalize(expr), do: {:ok, normalize_expr(expr)}

  def equivalent(a, b) do
    with {:ok, na} <- normalize(a), {:ok, nb} <- normalize(b) do
      if na == nb, do: {:ok, :proved, %{kernel: :algebra_v1}}, else: {:ok, :not_established, %{kernel: :algebra_v1}}
    end
  end

  defp normalize_expr({:op, :add, [a, b]}), do: add_expr(sort_terms([normalize_expr(a), normalize_expr(b)]))
  defp normalize_expr({:op, :multiply, [a, b]}), do: multiply_expr(sort_terms([normalize_expr(a), normalize_expr(b)]))
  defp normalize_expr(x), do: x

  defp sort_terms(xs), do: Enum.sort_by(xs, &inspect/1)
  defp add_expr([a, b]), do: {:op, :add, [a, b]}
  defp multiply_expr([a, b]), do: {:op, :multiply, [a, b]}
end
