defmodule Tiannara.ASC.Implementation.Plan do
  @moduledoc """
  Implementation Plan — structured design artifact bridging specification and code.

  Generated by Implementation.Planner from ProjectWorld requirements.
  Contains components, interfaces, workflows, storage models, validation rules,
  dependencies, and deployment units BEFORE any code is generated.

  Stored as standalone artifact in: data/asc_projects/<id>/implementation_plan.json
  Registered in Knowledge Archive for future reuse.
  """

  @derive Jason.Encoder
  defstruct [
    project_id: nil,
    architecture_style: :modular_monolith,

    # Core design artifacts
    components: [],        # [%Component{}]
    interfaces: [],        # [%Interface{}]
    workflows: [],         # [%Workflow{}]
    storage_models: [],    # [%StorageModel{}]
    validation_rules: [],  # [%ValidationRule{}]
    dependencies: [],      # [%Dependency{}]
    deployment_units: [],  # [%DeploymentUnit{}]

    # Quality metrics
    complexity_score: 0.0,
    confidence: 0.0,

    created_at: nil
  ]

  @type t :: %__MODULE__{
    project_id: String.t() | nil,
    architecture_style: atom(),
    components: [Component.t()],
    interfaces: [Interface.t()],
    workflows: [Workflow.t()],
    storage_models: [StorageModel.t()],
    validation_rules: [ValidationRule.t()],
    dependencies: [Dependency.t()],
    deployment_units: [DeploymentUnit.t()],
    complexity_score: float(),
    confidence: float(),
    created_at: DateTime.t() | nil
  }

  # ---------------------------------------------------------------------------
  # Nested Structs
  # ---------------------------------------------------------------------------

  defmodule Component do
    @moduledoc "A software component derived from capabilities"
    @derive Jason.Encoder
    defstruct [
      name: nil,
      responsibilities: [],  # List of capability names
      interfaces: [],        # List of interface names this component exposes
      dependencies: []       # List of other component names this depends on
    ]

    @type t :: %__MODULE__{
      name: String.t() | nil,
      responsibilities: [String.t()],
      interfaces: [String.t()],
      dependencies: [String.t()]
    }
  end

  defmodule Interface do
    @moduledoc "An API interface (endpoint or protocol)"
    @derive Jason.Encoder
    defstruct [
      name: nil,
      protocol: :http,  # :http, :grpc, :message_queue, :internal
      method: nil,      # GET, POST, PUT, DELETE (for HTTP)
      path: nil,        # URL path (for HTTP)
      input_schema: %{},
      output_schema: %{}
    ]

    @type t :: %__MODULE__{
      name: String.t() | nil,
      protocol: atom(),
      method: String.t() | nil,
      path: String.t() | nil,
      input_schema: map(),
      output_schema: map()
    }
  end

  defmodule Workflow do
    @moduledoc "A multi-step business process"
    @derive Jason.Encoder
    defstruct [
      name: nil,
      steps: [],           # List of step descriptions
      error_handling: :rollback  # :rollback, :compensate, :retry
    ]

    @type t :: %__MODULE__{
      name: String.t() | nil,
      steps: [String.t()],
      error_handling: atom()
    }
  end

  defmodule StorageModel do
    @moduledoc "A data persistence model (table, collection, etc.)"
    @derive Jason.Encoder
    defstruct [
      entity: nil,
      fields: [],          # List of field definitions
      constraints: [],     # List of constraints (unique, not_null, etc.)
      indexes: []          # List of indexes for performance
    ]

    @type t :: %__MODULE__{
      entity: String.t() | nil,
      fields: [map()],
      constraints: [String.t()],
      indexes: [String.t()]
    }
  end

  defmodule ValidationRule do
    @moduledoc "A validation rule derived from invariants"
    @derive Jason.Encoder
    defstruct [
      invariant_ref: nil,  # Reference to original invariant ID
      rule_type: nil,      # :uniqueness, :range, :format, :business_logic
      implementation: nil, # Description of validation logic
      severity: :error     # :error, :warning
    ]

    @type t :: %__MODULE__{
      invariant_ref: String.t() | nil,
      rule_type: atom() | nil,
      implementation: String.t() | nil,
      severity: atom()
    }
  end

  defmodule Dependency do
    @moduledoc "A dependency between components"
    @derive Jason.Encoder
    defstruct [
      from: nil,           # Source component name
      to: nil,             # Target component name
      type: :calls         # :calls, :publishes_to, :subscribes_to
    ]

    @type t :: %__MODULE__{
      from: String.t() | nil,
      to: String.t() | nil,
      type: atom()
    }
  end

  defmodule DeploymentUnit do
    @moduledoc "A deployable unit (service, container, function)"
    @derive Jason.Encoder
    defstruct [
      name: nil,
      resources: %{},      # %{cpu: "2 cores", memory: "512MB"}
      scaling: :none,      # :none, :horizontal, :vertical
      replicas: 1
    ]

    @type t :: %__MODULE__{
      name: String.t() | nil,
      resources: map(),
      scaling: atom(),
      replicas: non_neg_integer()
    }
  end

  # ---------------------------------------------------------------------------
  # Helper Functions
  # ---------------------------------------------------------------------------

  @doc """
  Create a new implementation plan for a project.
  """
  def new(project_id) do
    %__MODULE__{
      project_id: project_id,
      created_at: DateTime.utc_now()
    }
  end

  @doc """
  Calculate complexity score using deterministic formula.

  Complexity =
    Components * 1.0 +
    Dependencies * 2.0 +
    ValidationRules * 1.5 +
    Workflows * 3.0 +
    DeploymentUnits * 2.0
  """
  def calculate_complexity(%__MODULE__{} = plan) do
    component_factor = length(plan.components) * 1.0
    dependency_factor = length(plan.dependencies) * 2.0
    validation_factor = length(plan.validation_rules) * 1.5
    workflow_factor = length(plan.workflows) * 3.0
    deployment_factor = length(plan.deployment_units) * 2.0

    Float.round(component_factor + dependency_factor + validation_factor + workflow_factor + deployment_factor, 2)
  end

  @doc """
  Estimate confidence based on completeness of planning artifacts.
  """
  def estimate_confidence(%__MODULE__{} = plan) do
    has_components = if length(plan.components) > 0, do: 0.3, else: 0.0
    has_interfaces = if length(plan.interfaces) > 0, do: 0.2, else: 0.0
    has_validation = if length(plan.validation_rules) > 0, do: 0.2, else: 0.0
    has_storage = if length(plan.storage_models) > 0, do: 0.15, else: 0.0
    has_deployment = if length(plan.deployment_units) > 0, do: 0.15, else: 0.0

    Float.round(has_components + has_interfaces + has_validation + has_storage + has_deployment, 2)
  end
end
