defmodule Tiannara.Agency.Models do
  @moduledoc """
  Core data structures for the Agency Foundation (Omega.A).
  These models represent the primitives of Tiannara's continuous agency:
  observations, hypotheses, experiments, and integrated knowledge.
  """

  defmodule Observation do
    @moduledoc "A raw signal collected from a subsystem during the heartbeat cycle."
    defstruct [
      :id, :timestamp, :source, :metric_name, :value, :baseline, :delta, :delta_percent,
      context: %{},
      quality: 1.0
    ]
  end

  defmodule AgencyEvent do
    @moduledoc """
    A classified, prioritized epistemic event emitted by the Sentinel Heartbeat.
    This is the unit of work that drives the Research Director.
    """
    defstruct [
      :id, :timestamp, :source, :category, :severity, :observation_summary, :interpretation,
      causal_hypotheses: [],
      evidence: [],
      impact: 0.0,
      confidence: 0.0,
      urgency: 0.0,
      priority_score: 0.0,
      requires_investigation: false,
      requires_human_notification: false,
      metadata: %{}
    ]
  end

  defmodule Hypothesis do
    @moduledoc """
    A testable hypothesis generated by the Research Director from an agency event.
    Follows the scientific method: observation -> hypothesis -> prediction -> test.
    """
    defstruct [
      :id, :timestamp, :event_id, :statement, :prediction, :falsification_criteria, :status,
      required_evidence: [],
      priority_score: 0.0,
      priority_breakdown: %{},
      confidence: 0.0,
      experiment_id: nil
    ]
  end

  defmodule Experiment do
    @moduledoc """
    A structured experiment designed to test a hypothesis.
    Must include rollback plan and failure conditions (Verification First).
    """
    defstruct [
      :id, :timestamp, :hypothesis_id, :experiment_type, :design,
      :success_criteria, :rollback_plan, :status,
      variables: %{},
      controls: [],
      failure_conditions: [],
      expected_duration_cycles: 0,
      resource_cost: 0,
      risk_level: :low,
      requires_human_approval: false,
      results: nil
    ]
  end

  defmodule ExperimentResult do
    @moduledoc "Outcome of a completed experiment with evaluated evidence."
    defstruct [
      :id, :experiment_id, :timestamp, :recommendation,
      success: false,
      metrics: %{},
      evidence_items: [],
      confidence_delta: 0.0,
      unexpected_findings: []
    ]
  end

  defmodule KnowledgeRecord do
    @moduledoc """
    An integrated knowledge record. Moves data -> information -> knowledge -> principle.
    Stored in Reality Graph and Memory for future reasoning improvement.
    """
    defstruct [
      :id, :timestamp, :source_event_id, :source_hypothesis_id,
      :source_experiment_id, :domain, :content, :knowledge_level,
      confidence: 0.0,
      supporting_evidence: [],
      contradictions: [],
      reuse_count: 0,
      superseded_by: nil
    ]
  end

  defmodule CognitionCycleState do
    @moduledoc "Tracks the state of the continuous cognition cycle."
    defstruct [
      :cycle_id, :started_at, :last_completed_at, :status,
      observations_collected: 0,
      events_emitted: 0,
      hypotheses_generated: 0,
      experiments_run: 0,
      knowledge_integrated: 0,
      cycle_duration_ms: 0
    ]
  end
end
