{:ok, _} = Application.ensure_all_started(:tiannara)
Process.sleep(1500)
report = Tiannara.CEL.Kernel.boot_report()
IO.puts("EOS status: #{report.status} failed_critical: #{inspect(report.failed_critical)} runtime: #{Tiannara.CEL.Kernel.runtime_state()}")
IO.puts("DiscoverySupervisor whereis: #{inspect(Process.whereis(Tiannara.Discovery.DiscoverySupervisor) != nil)} health: #{inspect(Tiannara.Discovery.DiscoverySupervisor.health())}")
IO.puts("DiscoveryEngine whereis: #{inspect(Process.whereis(Tiannara.Discovery.DiscoveryEngine) != nil)}")
IO.puts("DiscoveryMetrics whereis: #{inspect(Process.whereis(Tiannara.Discovery.DiscoveryMetrics) != nil)}")
IO.puts("EventStore healthy: #{Tiannara.CEL.Services.EventStore.healthy?()} ExecutiveMemory healthy: #{Tiannara.CEL.Services.ExecutiveMemory.health()}")
cc = Tiannara.ControlCenter.status()
IO.puts("ControlCenter has discovery_engine: #{Map.has_key?(cc.subsystems, :discovery_engine)} discovery_scheduler: #{Map.has_key?(cc.subsystems, :discovery_scheduler)}")
