defmodule Tiannara.Meta.Epistemics.EpistemicThermodynamics do
  @moduledoc """
  Phase 5F.7 — Epistemic Thermodynamics

  Computes computational pressure and instability introduced by observers'
  epistemology / knowledge mass and system contradiction density.
  """

  @doc """
  Computes the thermodynamic pressure generated by an observer's knowledge mass
  interacting with the current contradiction density.
  """
  def compute_pressure(knowledge_mass, contradiction_density) do
    :math.log(knowledge_mass + 1.0) * (1.0 + contradiction_density)
  end
end
