FROM hexpm/elixir:1.18.3-erlang-27.3.3-alpine-3.21 AS build

RUN apk add --no-cache build-base git

WORKDIR /app

ENV MIX_ENV=prod

COPY mix.exs mix.lock ./
COPY config/ config/
COPY apps/ apps/

RUN mix deps.get --only prod
RUN mix compile --warnings-as-errors
RUN mix phx.digest
RUN mix release

FROM alpine:3.21 AS app

RUN apk add --no-cache openssl ncurses-libs libstdc++

WORKDIR /app

COPY --from=build /app/_build/prod/rel/observatory_api ./

EXPOSE 4000

ENV PHX_SERVER=true

CMD ["/app/bin/server"]
