FROM node:22-alpine AS build

WORKDIR /app

COPY apps/observatory_ui/package.json apps/observatory_ui/package-lock.json ./
RUN npm ci

COPY apps/observatory_ui/ .
RUN npm run build

FROM node:22-alpine AS app

WORKDIR /app

COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/next.config.ts ./

EXPOSE 3000

CMD ["npm", "start"]
